### ISSUE TITLE
semver release

### ISSUE THREAD

**Issue by coreyfarrell** [sindresorhus/decamelize#10]
Sorry to bother you @sindresorhus but I had assumed the change I made last night would have to become a semver-major release.  Not sure if releasing as 1.2.0 instead of 2.0.0 was intentional or not but I wanted to make sure you noticed.

In the future I could tag the commit message first like like `BREAKING: ES2015ify and require Node 4` to make sure it's noticed?

**Comment by sindresorhus** [comment]
I didn’t release anything. Take another look at the commit history. I usually don’t do new releases when there are no user facing changes or speed benefits.
