### ISSUE TITLE
consider appropriate regexp implementations for different runtimes

### ISSUE THREAD

**Issue by kmohrf** [sindresorhus/decamelize#14]
Hi,

I recently noticed that the build size of my browser bundle increased and found a full copy of xregexp inside. Though I understand that this module is primarly focused on node as runtime, there should be a way to handle other runtimes with a little more grace.

There is a Babel plugin called [unicode-property-regex](https://babeljs.io/docs/en/next/babel-plugin-proposal-unicode-property-regex.html) based on [regexpu](https://github.com/mathiasbynens/regexpu) that transforms regular expressions with the unicode flag to es5-compatible code.

this code:

```js
'use strict';

module.exports = (text, separator) => {
	if (typeof text !== 'string') {
		throw new TypeError('Expected a string');
	}

	separator = typeof separator === 'undefined' ? '_' : separator;

	const regex1 = /([\p{Ll}\d])(\p{Lu})/gu;
	const regex2 = /(\p{Lu}+)(\p{Lu}[\p{Ll}\d]+)/gu;

	return text
		.replace(regex1, `$1${separator}$2`)
		.replace(regex2, `$1${separator}$2`)
		.toLowerCase();
};
```

already passes the tests when transformed with regexpu. The transformed file is currently about 23kb in size but maybe it’s possible to mangle the character classes so that multiple occurrences don’t increase the size. still: 23kb is better than the ~75kb xregexp dependency.

I think it might be a good idea to:
* provide a CommonJS module with the xregexp dependency
* an EcmaScript module with the new /u flag (as far as I can see ES6 modules are still experimental in Node, so it’s reasonable to assume that any code that uses native modules will use Node>=10)
* an es-5 compatible browser module transformed by regexpu

As far as I know it should be possible to [modify the package.json](https://github.com/webpack/webpack/issues/4674#issuecomment-355853969) file in a way that those modules will be picked up automatically. I’ve never done that myself though.

Thank you for your time! If I can help in any way feel free to reach out.

**Comment by icd2k3** [comment]
I would appreciate this too! I may have time to make a PR in the near future. I use `humanize-string` (which uses `decamelize`) for my [project](https://github.com/icd2k3/react-router-breadcrumbs-hoc) and recently discovered my bundle size is like 99% `xregexp`. My total bundle size would go from 220kb -> 15kb if it was not imported within this project.

**Comment by sindresorhus** [comment]
If you don't need Unicode support, you could just use version 1.2.0.

I'm not really interested in adding a Babel compile-step. I'm just gonna require Node.js 10 at some point and use the native regex instead of `xregexp`.

**Comment by icd2k3** [comment]
Thanks @sindresorhus! That makes sense. Do you have any rough timeline in mind for requiring Node 10?

**Comment by kmohrf** [comment]
I don’t think unicode support and optimized size are mutually exclusive requirements. So falling back to 1.2.0 may not be an option for everyone. Anyway: If you don’t want the babel step, then I guess that this issue should be closed?
