### ISSUE TITLE
bug in firefox and decamelize 4

### ISSUE THREAD

**Issue by s00d** [sindresorhus/decamelize#24]
Hello, after upgrading to version 4, I get the error in firefox:
```
SyntaxError: invalid identity escape in regular expression
```

Example: https://codesandbox.io/s/pedantic-margulis-r7wee (need to open firefox)

**Comment by sindresorhus** [comment]
This is not a bug in Decamelize. Firefox doesn't support modern regex features used here.

https://bugzilla.mozilla.org/show_bug.cgi?id=1361876

If you need to support Firefox, you should probably stay on the previous version.
