### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by JanStevens** [sindresorhus/decamelize#25]
Hello,

Since v4.0.0 this package does not support any release of Firefox. Apparently firefox is way behind in the implementation of Regexp lookup groups and using the `/u` flag.

Any chance this could be reverted back? Or at least a warning could be added that upgrading will cause issue for firefox. Apparently the JS world depends on this package

Regards

**Comment by sindresorhus** [comment]
Sorry, I'm not interested in reverting the change. Dropping the heavy `xregexp ` dependendy benefits Node.js users, which is the main target audience.

If you need Firefox support, just stay on version 3 for now.

**Comment by tenjojeremy** [comment]
@JanStevens Use this if you need Firefox 

https://ourcodeworld.com/articles/read/608/how-to-camelize-and-decamelize-strings-in-javascript

**Comment by sindresorhus** [comment]
Latest Firefox now supports modern regex features.

**Comment by andreasvirkus** [comment]
(For people of the future...) Same goes for Safari with version 4 or 5, as it [doesn't support lookbehind](https://caniuse.com/js-regexp-lookbehind). You'll see an error:

```
SyntaxError: Invalid regular expression: invalid group specifier name
```

But downgrading works a-ok 👌
