### ISSUE TITLE
preserveConsecutiveUppercase

### ISSUE THREAD

**Issue by donkeyDau** [sindresorhus/decamelize#29]
In the latest release of https://github.com/sindresorhus/camelcase the option preserveConsecutiveUppercase was introduced. I need a comparable option for `decamelize`.

@sindresorhus Do you see that in the scope of this package?

I tried to fiddle around with the code but there would be probably some edge cases to be handled and more options to be introduced to meet the complexity of this. This would kind of ruin the the minimalist beauty of the code ...

**Comment by sindresorhus** [comment]
You mean you want `fooBAR` => `foo_BAR`, right? I guess that makes sense. But it would have to be a good PR that came with lots of tests, docs, and types.

**Comment by donkeyDau** [comment]
> You mean you want fooBAR => foo_BAR, right?
Yes.

> But it would have to be a good PR that came with lots of tests, docs, and types.
I'll give it a try.
