### ISSUE TITLE
The library breaks in Safari

### ISSUE THREAD

**Issue by stdavis** [sindresorhus/decamelize#36]
Safari [does not yet support](https://caniuse.com/js-regexp-lookbehind) [regex lookbehinds](https://github.com/sindresorhus/decamelize/blob/55200914ae171eb1962a267c51878fef90005546/index.js#L7).

I'm not sure if Safari support is a desired feature for this library or not but thought that I would let you know.

**Comment by LitoMore** [comment]
Sindre is already mentioned in https://github.com/sindresorhus/decamelize/releases/tag/v4.0.0.

Please stay on version 3 if you need support Safari.

**Comment by bryan-gilbert** [comment]
It's probably too little too late for Safari but they finally fixed the problem with Lookbehind RegExp
https://bugs.webkit.org/show_bug.cgi?id=174931
No release date as of yet
