### ISSUE TITLE
Invalid regex error on iOS - invalid group specifier name

### ISSUE THREAD

**Issue by PavelJiranek** [sindresorhus/decamelize#38]
Using the library v6 crashes a web app on iOS because of this regex

![image](https://user-images.githubusercontent.com/31501883/161423944-f73c4311-0a53-4960-85e7-9720b30c7b1e.png)

Would it be please possible to make it iOS compliant?

**Comment by sindresorhus** [comment]
From the readme:

> If you need Safari support, https://github.com/sindresorhus/decamelize/issues/24 https://github.com/sindresorhus/decamelize/issues/36 [until they implement](https://caniuse.com/js-regexp-lookbehind) regex lookbehinds.

**Comment by PavelJiranek** [comment]
> From the readme:
> 
> > If you need Safari support, #24 #36 [until they implement](https://caniuse.com/js-regexp-lookbehind) regex lookbehinds.

Thanks, I have solved it by downgrading to v4. However, what is strange, is that the error occurred also in Chrome and Brave on iOS, not only Safari, despite the fact that Chrome should support lookbehinds.
