### ISSUE TITLE
Make tests faster

### ISSUE THREAD

**Issue by tkdeshpande** [sindresorhus/decamelize#39]
Ava does not support displaying execution time and thereby leaving no traceability for execution duration. We can add Jest which is lighter, better maintained & faster even without concurrency.

**Comment by sindresorhus** [comment]
Jest is definitely not lighter. And also not better maintained (more frequent commits does not mean better maintained, look at the amount of open issues). AVA is more than fast enough. Tests run in less than a second. And it should be even faster when upgrading to AVA v4.

**Comment by sindresorhus** [comment]
I upgraded to AVA v4 and measured it compared to your Jest pull request:

- Jest: 0.47
- AVA 4: 0.31

**Comment by sindresorhus** [comment]
Jest measurement numbers are also faulty as they don't measure the startup time.
