### ISSUE TITLE
decamelizeKeys?

### ISSUE THREAD

**Issue by ides15** [sindresorhus/decamelize#41]
Is it possible to add a `decamelizeKeys(obj)` operation? I'm looking for an inverse of `camelcaseKeys(obj)`.

**Comment by sindresorhus** [comment]
Nothing yet. But the plan is to add it to https://github.com/sindresorhus/camelcase-keys/issues/70

**Comment by sindresorhus** [comment]
Now available at: https://github.com/sindresorhus/decamelize-keys
