### ISSUE TITLE
if the separator is |, this function does not work

### ISSUE THREAD

**Issue by saurik** [sindresorhus/decamelize#5]
You seem to have fallen prey to a "regular expression injection attack" :(.

**Comment by sindresorhus** [comment]
Ah, yeah... It didn't use a regex initially. https://github.com/sindresorhus/decamelize/commit/2ccddbe27bac92ba3828bc36ac5cb5b20e0ca923

**Comment by sindresorhus** [comment]
Fixed in 1.1.2 :)
