### ISSUE TITLE
Handling multiple-letter words (abbreviations-alike)

### ISSUE THREAD

**Issue by luileito** [sindresorhus/decamelize#7]
Hi, 

Would this module be able to handle these cases?

* `URLString` becomes `urlstring` but it should be `url_string`.
* `myURLString` becomes `my_u_rlstring` but it should be `my_url_string`.

**Comment by sindresorhus** [comment]
You're right. That would be better behavior. I don't have the time right now to do it, but PR welcome :)

**Comment by portgasd666** [comment]
Im working on this. So the expected behavior is that any consecutive uppercase letters get grouped together ?

**Comment by sindresorhus** [comment]
@portgasd666 Consecutive except the last one. `URLString` => `URL` & `String` => `URL_String` => `url_string`.

**Comment by portgasd666** [comment]
I just ran npm test (without making any changes) and it just gives me 0 tests passed. changing an existing test to fail doesnt change. Any idea why the tests are not being run ?

**Comment by sindresorhus** [comment]
That's weird. It works for me. Just tried.

**Comment by portgasd666** [comment]
Hmm .. what version of Node am I supposed to be using? Could that be an issue ?

**Comment by portgasd666** [comment]
Okay,  ignore that. Cloned my fork again and installed dependencies and it worked ..

**Comment by portgasd666** [comment]
Okay, I'm handling cases such as myURLString and URLString. 

Now i just need some help as to how best to submit a pull request. Right now i have one commit just to resolve some merge conflicts when a fetched and merged upstream today after a long time and another to actually make the changes. Should i just submit it or am i supposed to clean it up somehow ?
